package com.wuxue.view.enums;

public enum ActionEnum {
    COUNTBY,
    SAVEZHYOU,
    FINDPARENTISNULL,
    FINDPARENTISNOTNULL,
    UPDATESORT,
    FINDZHYOU,
    GETSTUDENT,
    FIND,
    SELECTBY,
    DELETE,
    SAVE,
    LOGIN,
    DOMAINROLE,
    GETCODE,
    SUBMIT,
    AUDIT,
    CANCEL,
    GETNOTPLACEMENT,
    RETREAT,
    STUDENTRETURNCLASS,
    UPDATESTATUS,
    SELECTBYUSER,
    SAVEALL,
    FINDEMPLOYEESTUDENT,
    RECEIPTSAVEPAYABLES,
    REFUND,
    FINDCLASSSTUDENTSCORES ,//班级学生成绩
    SAVESTUDENTZHY,
    UPDATEPASSWORD,
    GETUSERROLE,
    FINDNUM,
    FINDTEACHER,
    FINDCLASSINFOTEACHER,//班级老师
    GETTEACHERCOURSE,//老师课程
    FINDCLASSSCHODULE,
    FINDCLASSINFOROOM,//班级教室
    SAVELOOP,
    FINDCLASSFORCOURSE,
    SELECTIVECHECK,
    SAVEAUDIT , //保存直接审核
    FINDSCHOOLREPORT,
    GOTOSCHOOL,
    FINDARREARSSTUDENT, //查询欠费学生
    FINDBYUSER,//根据用户查询
    STATISTICS, //统计
    QUERYANSWERLIST,//根据题目和选项查询家长
    FINDLIST, //查询班级活动
    FINDINFO,
    SAVEORUPDATE,
    SAVEORUPDATERACERECORD,  //保存竞赛记录
    FINDRACERECORDINFOBYID, //竞赛详情
    FINDRACERECORDLISTBYCLASSINFOID, // 查询班级竞赛记录
    GETPAYRECORDLIST , //点餐支付记录
    GETDISCUSSCOUNTLISTFORPC,//统计留言板数量
    FINDBYBUSID,
    MEALSTATISTICS,   //选餐统计
    SELECTFORRECORD , //学生点餐记录
    REVERSELINES,  //反向生成校车路线
    GETDISCUSSLISTFORPC, //获取留言回复总列表
    THEACHERREPLY,//留言回复
    GETNUTRITIONANALYSIS ,//营养分析
    CLASSON , // 班级升班
    FINDELECSCHEDULE , //查询兴趣选课
    SAVEFORSCHE ,// 保存班级学生
    DELETEBYCLASSANDSTU, //删除自选课程班级学生对应关系
    QUERYDEFAULT ,   //查询套餐默认
    FINDBYCLASSINFO,
    FINDCLASSDOUBLESCHODULE ,//单双周课表
    FINDEMPDOUBLESCHODULE, //老师双周课表
    QUERYCODE,//查询编号
    GETSTUDENTIDCODE,  // 获取学号编码
    GETURL,  //获得学校logo
    GETCLASSINFO,
    FINDBYMAP,
    SAVEELECTIVE,
    GETCOST,
    FINDFROREFUND

}
