package com.wuxue.view.enums;

public enum ActionEnum {
    COUNTBY,
    SAVEZHYOU,
    FINDPARENTISNULL,
    FINDPARENTISNOTNULL,
    UPDATESORT,
    FINDZHYOU,
    GETSTUDENT,
    FIND,
    SELECTBY,
    DELETE,
    SAVE,
    LOGIN,
    DOMAINROLE,
    GETCODE,
    SUBMIT,
    AUDIT,
    CANCEL,
    GETNOTPLACEMENT,
    RETREAT,
    STUDENTRETURNCLASS,
    UPDATESTATUS,
    SELECTBYUSER,
    SAVEALL,
    FINDEMPLOYEESTUDENT,
    RECEIPTSAVEPAYABLES,
    REFUND,
    FINDCLASSSTUDENTSCORES ,//班级学生成绩
    SAVESTUDENTZHY,
    UPDATEPASSWORD,
    GETUSERROLE,
    FINDNUM,
    FINDTEACHER,
    FINDCLASSINFOTEACHER,//班级老师
    GETTEACHERCOURSE,//老师课程
    FINDCLASSSCHODULE,
    FINDCLASSINFOROOM,//班级教室
    SAVELOOP,
    FINDCLASSFORCOURSE,
    SELECTIVECHECK,
    FINDGUANQIAO, //冠桥产品列表
    STUDENTLOGIN,//学生登录
    FINDGUANQIAOBY,
    FINDBYNOTORDER
}
